### ISSUE TITLE
Metric error

### ISSUE THREAD

**Issue by FlacoRene** [GoogleCloudPlatform/monitoring-dashboard-samples#231]
Hello,

When trying to copy the integration dashboard, or create a custom dashboard from the json, the metrics listed in the json don't seem to exist or at least not recognized by Google. Here is an error I receive when trying to copy the integration dashboard. Is there by chance something I'm missing?

There was an error persisting the dashboard changes
Field mosaicLayout.tiles[10].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'workload.googleapis.com/sqlserver.user.connection.count'. Field mosaicLayout.tiles[11].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'workload.googleapis.com/sqlserver.user.connection.count'. Field mosaicLayout.tiles[12].widget.xyChart.dataSets[0].timeSeriesQuery.timeSeriesQueryLanguage has an invalid value: Could not find a metric named 'workload.googleapis.com/sqlserver.user.connection.count'.

Tracking number: c2129256541987453

![image](https://user-images.githubusercontent.com/60758565/179268511-88dd8f38-fa8c-4626-956c-3fc0cb48b3b0.png)
![image](https://user-images.githubusercontent.com/60758565/179268681-56a9c72c-4bdb-4483-bd8d-1ef5f5577780.png)

**Comment by EvanSimpson** [comment]
Hi @FlacoRene this dashboard requires the _v2_ MSSQL metrics receiver to be configured in the Ops Agent (version 2.18.1 required) and will not work with the v1 metrics. It looks like the new configuration hasn't made it into the official cloud documentation yet, but you can still find the proper configuration in the Ops Agent repository here https://github.com/GoogleCloudPlatform/ops-agent/blob/master/docs/mssql.md#configuration

**Comment by FlacoRene** [comment]
Hey @EvanSimpson That was it! Looks like once I did that configuration it worked right away. Thanks for clarifying that the documentation isn't quite up to date. Guess my timing was off. Thanks again!

**Comment by EvanSimpson** [comment]
Glad you were able to get it working!
