### ISSUE TITLE
- - [ ] @davidcole1340   DO I REALLY NEED THIS ??????

### ISSUE THREAD

**Issue by ralphstone1** [GoogleCloudPlatform/monitoring-dashboard-samples#43]
- - [ ] @davidcole1340   DO I REALLY NEED THIS ??????￼

__Originally posted by @ralphstone1 in https://github.com/discord/discord-api-docs/issues/3153#issuecomment-865049707__

__Originally posted by @ralphstone1 in https://github.com/sponnusa/enterprise-log-search-and-archive/issues/243__

**Comment by xiangshen-dk** [comment]
It seems not related.
