### ISSUE TITLE
Is it safe to run terraform destroy?

### ISSUE THREAD

**Issue by rafaeljesus** [GoogleCloudPlatform/monitoring-dashboard-samples#7]
I just want to double-check if it's safe to run terraform destroy via the terraform? My main concern is https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/blob/3a36e65321a8c95260ab092a54b26049ce9fbaec/terraform/main.tf#L33

Which I am not too familiar with, I am aware that this resource is non-authoritative, while `google_project_services` is authoritative, so I want to double-check with you first

thank you

**Comment by xiangshen-dk** [comment]
It should be safe to run destroy. The enabled APIs will not be disabled since we specify **disable_on_destroy** to false.

Also, the dashboard itself doesn't store any metric data. If it's destroyed we can easily recreate it.

**Comment by rafaeljesus** [comment]
thanks
