### ISSUE TITLE
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

### ISSUE THREAD

**Issue by bombastictranz** [GoogleCloudPlatform/monitoring-dashboard-samples#733]
Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

View this [failed invocation](https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/pull/732/checks?check_run_id=22346012727) of the CLA check for more information.

For the most up to date status, view the checks section at the bottom of the pull request.

_Originally posted by @google-cla[bot] in https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/issues/732#issuecomment-1980962524_

**Comment by EvanSimpson** [comment]
If you'd like to contribute to this repository, please accept the CLA and adhere to our contribution guidelines.
