### ISSUE TITLE
Is there a way to see these dashboards in a gallery?

### ISSUE THREAD

**Issue by lucafaggianelli** [GoogleCloudPlatform/monitoring-dashboard-samples#758]
It would be nice to have a webpage where you can see all these dashboards, filter by features, see the preview images and eventually click on the deploy button.

Happy to make a tiny website if anyone interested

**Comment by EvanSimpson** [comment]
The Cloud Console currently exposes all of these dashboard at https://console.cloud.google.com/monitoring/dashboards, behind the "Sample Library" tab. From there you can select "preview" to see the preview images, descriptions, and import to your current cloud project.

![image](https://github.com/GoogleCloudPlatform/monitoring-dashboard-samples/assets/1757661/4075ef45-7050-47cc-9165-267cb6aa2fd2)

Filtering by features is a great suggestion, and I can pass along this request internally, thanks!
