### ISSUE TITLE
import script: Support for units

### ISSUE THREAD

**Issue by bwplotka** [GoogleCloudPlatform/monitoring-dashboard-samples#808]
Looks like import script does not support units.

e.g. https://grafana.com/grafana/dashboards/14061-go-runtime-metrics/ importing results in graps without correct units:

<img width="1630" alt="image" src="https://github.com/user-attachments/assets/ebcfa78f-eadc-4016-9aa8-f794350c625e">

Would be nice to add that 👍🏽

**Comment by stevezease** [comment]
Hey @bwplotka, thank you for filing this! We are beginning to shift the conversion logic source of truth to be based internally. Let me create a ticket to track this internally and bring this to the attention of our pms.

**Comment by stevezease** [comment]
Ticket was created internally, will see if I can address this after our upcoming feature launch
